spring.application.name=scheduler-api
# --- DYNAMIC CONFIGURATION ---
# Syntax: ${ENV_VAR_NAME:DefaultValue}
# If the environment variable exists (Cloud), use if. If not, use the default (Local).
# 1. Database
# The hardcoded localhost to read from 'DB_URL', 'DB_USER', etc.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/scheduler}
spring.datasource.username=${DB_USERNAME:samn}
spring.datasource.password=${DB_PASSWORD:1738}
# 2. Port
# Render assigns a random port and puts it in the 'PORT' env var.
server.port=${PORT:8080}
# 3. Hibernate Settings (The Engine Tuning)
# "update" means: If I add a field in Java, add a column in DB automatically.
spring.jpa.hibernate.ddl-auto=create-drop
# Show us the SQL queries in the console (Great for debugging)
spring.jpa.show-sql=true
# Use the correct dialect for Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
